name: Deploy web17

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Konfiguracja klucza SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 ${{ secrets.PROD_HOST }} >> ~/.ssh/known_hosts

      - name: Utworzenie i wyslanie skryptu wdrazajacego
        run: |
          cat << 'SCRIPT' > deploy.sh
          #!/bin/bash
          set -x
          export HOME=/home/web17
          export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
          cd ~/web
          git config --global --add safe.directory ~/web
          git config --global --add safe.directory /var/www/clients/client1/web17/web
          git pull origin main 2>&1
          SCRIPT
          
          chmod +x deploy.sh
          scp -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no deploy.sh web17@${{ secrets.PROD_HOST }}:~/deploy.sh

      - name: Uruchomienie skryptu na serwerze
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no web17@${{ secrets.PROD_HOST }} "bash ~/deploy.sh"