name: Deploy web17

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to web17
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: web17
          key: ${{ secrets.PROD_SSH_KEY }}
          port: 22
          script: |
            set -x
            cd /var/www/clients/client1/web17/web
            git config --global --add safe.directory /var/www/clients/client1/web17/web
            git pull origin main 2>&1
